--------------------------------------------------------------------------------
-- 1. DROP OLD OBJECTS IF THEY EXIST
--    Safe to run multiple times
--------------------------------------------------------------------------------
begin
  begin
    dbms_scheduler.drop_job('JOB_REFRESH_OCI_COMPARTMENTS', force => true);
  exception
    when others then
      if sqlcode != -27475 then raise; end if; -- job does not exist
  end;
end;
/
    
begin
  execute immediate 'drop procedure refresh_oci_compartments';
exception
  when others then
    if sqlcode != -4043 then raise; end if; -- object does not exist
end;
/

begin
  execute immediate 'drop table adb_oci_compartments purge';
exception
  when others then
    if sqlcode != -942 then raise; end if; -- table does not exist
end;
/

begin
  execute immediate 'drop table adb_oci_compartments_log purge';
exception
  when others then
    if sqlcode != -942 then raise; end if; -- table does not exist
end;
/
--------------------------------------------------------------------------------
-- 2. CREATE LOG TABLE
--------------------------------------------------------------------------------
create table adb_oci_compartments_log (
  run_id         number generated by default as identity primary key,
  run_start_ts   timestamp with time zone not null,
  run_end_ts     timestamp with time zone,
  status         varchar2(30) not null,
  rows_loaded    number,
  error_message  varchar2(4000)
);
/
--------------------------------------------------------------------------------
-- 3. CREATE TARGET TABLE
--------------------------------------------------------------------------------
create table adb_oci_compartments (
  compartment_ocid         varchar2(500) primary key,
  parent_compartment_ocid  varchar2(500),
  tenancy_ocid             varchar2(500) not null,
  name                     varchar2(255) not null,
  description              varchar2(4000),
  time_created             timestamp with time zone,
  lifecycle_state          varchar2(50),
  inactive_status          number,
  is_accessible            number(1),
  region_name              varchar2(100),
  hierarchy_level          number,
  hierarchy_path           varchar2(4000),
  last_refresh_ts          timestamp with time zone not null
);
/

create index adb_oci_compartments_ix1
  on adb_oci_compartments (parent_compartment_ocid);
/

create index adb_oci_compartments_ix2
  on adb_oci_compartments (last_refresh_ts);
/

create index adb_oci_compartments_ix3
  on adb_oci_compartments (name);
/
--------------------------------------------------------------------------------
-- 4. CREATE PROCEDURE
--------------------------------------------------------------------------------
create or replace procedure refresh_oci_compartments
as
  ------------------------------------------------------------------------------
  -- CHANGE THESE 3 VALUES FOR YOUR ENVIRONMENT
  ------------------------------------------------------------------------------
  c_tenancy_id  constant varchar2(500) := 'ocid1.tenancy.oc1..aaaaaaaamy3a46ljb5gdtruftfg7xtuatc5ymgeob3sivuuao34sjbx3tk3q';
  c_region      constant varchar2(50)  := 'us-phoenix-1';
  c_credential  constant varchar2(100) := 'OCI$RESOURCE_PRINCIPAL';

  ------------------------------------------------------------------------------
  -- OPTIONAL TUNING
  ------------------------------------------------------------------------------
  c_page_size   constant number := 1000;

  ------------------------------------------------------------------------------
  -- API OBJECTS
  ------------------------------------------------------------------------------
  response        dbms_cloud_oci_id_identity_list_compartments_response_t;
  response_body   dbms_cloud_oci_identity_compartment_tbl;

  ------------------------------------------------------------------------------
  -- LOGIC VARIABLES
  ------------------------------------------------------------------------------
  l_next_page     varchar2(4000)           := null;
  l_is_first      boolean                  := true;
  l_run_id        number;
  l_run_start     timestamp with time zone := systimestamp;
  l_rows_loaded   number                   := 0;

begin
  ------------------------------------------------------------------------------
  -- A. START LOGGING
  ------------------------------------------------------------------------------
  insert into adb_oci_compartments_log (run_start_ts, status)
  values (l_run_start, 'RUNNING')
  returning run_id into l_run_id;

  commit;

  ------------------------------------------------------------------------------
  -- B. MAIN FETCH LOOP
  ------------------------------------------------------------------------------
  loop
    if l_is_first then
      response := dbms_cloud_oci_id_identity.list_compartments(
        compartment_id            => c_tenancy_id,
        limit                     => c_page_size,
        access_level              => 'ACCESSIBLE',
        compartment_id_in_subtree => 1,
        lifecycle_state           => 'ACTIVE',
        credential_name           => c_credential,
        region                    => c_region
      );
      l_is_first := false;
    else
      response := dbms_cloud_oci_id_identity.list_compartments(
        compartment_id            => c_tenancy_id,
        limit                     => c_page_size,
        page                      => l_next_page,
        access_level              => 'ACCESSIBLE',
        compartment_id_in_subtree => 1,
        lifecycle_state           => 'ACTIVE',
        credential_name           => c_credential,
        region                    => c_region
      );
    end if;

    response_body := response.response_body;

    if response_body is not null and response_body.count > 0 then
      for i in 1 .. response_body.count loop
        merge into adb_oci_compartments tgt
        using (
          select
            response_body(i).id                       as compartment_ocid,
            response_body(i).compartment_id           as parent_compartment_ocid,
            c_tenancy_id                              as tenancy_ocid,
            response_body(i).name                     as name,
            response_body(i).description              as description,
            cast(response_body(i).time_created as timestamp with time zone) as time_created,
            response_body(i).lifecycle_state          as lifecycle_state,
            response_body(i).inactive_status          as inactive_status,
            case
              when response_body(i).is_accessible then 1
              else 0
            end                                       as is_accessible,
            c_region                                  as region_name
          from dual
        ) src
        on (tgt.compartment_ocid = src.compartment_ocid)
        when matched then update set
          tgt.parent_compartment_ocid = src.parent_compartment_ocid,
          tgt.tenancy_ocid            = src.tenancy_ocid,
          tgt.name                    = src.name,
          tgt.description             = src.description,
          tgt.time_created            = src.time_created,
          tgt.lifecycle_state         = src.lifecycle_state,
          tgt.inactive_status         = src.inactive_status,
          tgt.is_accessible           = src.is_accessible,
          tgt.region_name             = src.region_name,
          tgt.last_refresh_ts         = systimestamp
        when not matched then insert (
          compartment_ocid,
          parent_compartment_ocid,
          tenancy_ocid,
          name,
          description,
          time_created,
          lifecycle_state,
          inactive_status,
          is_accessible,
          region_name,
          last_refresh_ts
        ) values (
          src.compartment_ocid,
          src.parent_compartment_ocid,
          src.tenancy_ocid,
          src.name,
          src.description,
          src.time_created,
          src.lifecycle_state,
          src.inactive_status,
          src.is_accessible,
          src.region_name,
          systimestamp
        );

        l_rows_loaded := l_rows_loaded + 1;
      end loop;
    end if;

    ----------------------------------------------------------------------------
    -- PAGINATION
    ----------------------------------------------------------------------------
    l_next_page := null;

    if response.headers is not null then
      if response.headers.has('opc-next-page') then
        l_next_page := response.headers.get_string('opc-next-page');
      end if;
    end if;

    exit when l_next_page is null;
  end loop;

  ------------------------------------------------------------------------------
  -- C. BUILD HIERARCHY LEVEL AND PATH
  ------------------------------------------------------------------------------
  merge into adb_oci_compartments tgt
  using (
    with hier (compartment_ocid, parent_compartment_ocid, lvl, path) as (
      select
        compartment_ocid,
        parent_compartment_ocid,
        1 as lvl,
        cast(name as varchar2(4000)) as path
      from adb_oci_compartments
      where parent_compartment_ocid = c_tenancy_id

      union all

      select
        c.compartment_ocid,
        c.parent_compartment_ocid,
        h.lvl + 1,
        h.path || ' / ' || c.name
      from adb_oci_compartments c
      join hier h
        on c.parent_compartment_ocid = h.compartment_ocid
    )
    select
      compartment_ocid,
      lvl,
      path
    from hier
  ) src
  on (tgt.compartment_ocid = src.compartment_ocid)
  when matched then update set
    tgt.hierarchy_level = src.lvl,
    tgt.hierarchy_path  = src.path;

  ------------------------------------------------------------------------------
  -- D. MARK OLD ROWS AS DELETED IF NOT SEEN IN THIS RUN
  ------------------------------------------------------------------------------
  update adb_oci_compartments
     set lifecycle_state = 'DELETED',
         last_refresh_ts = systimestamp
   where last_refresh_ts < l_run_start
     and lifecycle_state <> 'DELETED';

  commit;

  ------------------------------------------------------------------------------
  -- E. LOG SUCCESS
  ------------------------------------------------------------------------------
  update adb_oci_compartments_log
     set run_end_ts  = systimestamp,
         status      = 'SUCCESS',
         rows_loaded = l_rows_loaded
   where run_id = l_run_id;

  commit;

exception
  when others then
    rollback;

    update adb_oci_compartments_log
       set run_end_ts    = systimestamp,
           status        = 'FAILED',
           rows_loaded   = l_rows_loaded,
           error_message = substr(sqlerrm, 1, 4000)
     where run_id = l_run_id;

    commit;
    raise;
end refresh_oci_compartments;
/
show errors
--------------------------------------------------------------------------------
-- 5. TEST RUN THE PROCEDURE ONCE
--------------------------------------------------------------------------------
begin
  refresh_oci_compartments;
end;
/
--------------------------------------------------------------------------------
-- 6. CREATE HOURLY SCHEDULER JOB
--------------------------------------------------------------------------------
begin
  dbms_scheduler.create_job (
    job_name        => 'JOB_REFRESH_OCI_COMPARTMENTS',
    job_type        => 'STORED_PROCEDURE',
    job_action      => 'REFRESH_OCI_COMPARTMENTS',
    start_date      => systimestamp,
    repeat_interval => 'FREQ=HOURLY;INTERVAL=1',
    enabled         => true,
    comments        => 'Refresh OCI compartments every 1 hour'
  );
end;
/
--------------------------------------------------------------------------------
-- 7. OPTIONAL: VERIFY JOB
--------------------------------------------------------------------------------
select job_name, enabled, state, repeat_interval
from user_scheduler_jobs
where job_name = 'JOB_REFRESH_OCI_COMPARTMENTS';
/
--------------------------------------------------------------------------------
-- 8. OPTIONAL: VIEW LATEST RUNS
--------------------------------------------------------------------------------
select *
from adb_oci_compartments_log
order by run_id desc;
/
--------------------------------------------------------------------------------
-- 9. OPTIONAL: VIEW COMPARTMENTS
--------------------------------------------------------------------------------
select
  compartment_ocid,
  parent_compartment_ocid,
  name,
  lifecycle_state,
  hierarchy_level,
  hierarchy_path,
  last_refresh_ts
from adb_oci_compartments
order by hierarchy_path nulls first, name;
/
