--------------------------------------------------------------------------------
-- OCI COMPARTMENTS PIPELINE FOR ADB
-- FULL VERSION
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 0. CLEANUP
--------------------------------------------------------------------------------
BEGIN
  DBMS_SCHEDULER.DROP_JOB('JOB_REFRESH_OCI_COMPARTMENTS', TRUE);
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE REFRESH_OCI_COMPARTMENTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ADB_OCI_COMPARTMENTS PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ADB_OCI_COMPARTMENTS_LOG PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

--------------------------------------------------------------------------------
-- 1. LOG TABLE
--------------------------------------------------------------------------------
CREATE TABLE ADB_OCI_COMPARTMENTS_LOG (
  RUN_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RUN_START_TS   TIMESTAMP WITH TIME ZONE NOT NULL,
  RUN_END_TS     TIMESTAMP WITH TIME ZONE,
  STATUS         VARCHAR2(30) NOT NULL,
  ROWS_LOADED    NUMBER,
  ERROR_MESSAGE  VARCHAR2(4000)
);
/

--------------------------------------------------------------------------------
-- 2. TARGET TABLE
--------------------------------------------------------------------------------
CREATE TABLE ADB_OCI_COMPARTMENTS (
  COMPARTMENT_OCID         VARCHAR2(500) PRIMARY KEY,
  PARENT_COMPARTMENT_OCID  VARCHAR2(500),
  TENANCY_OCID             VARCHAR2(500) NOT NULL,
  NAME                     VARCHAR2(255),
  DESCRIPTION              VARCHAR2(4000),
  TIME_CREATED             TIMESTAMP WITH TIME ZONE,
  LIFECYCLE_STATE          VARCHAR2(50),
  INACTIVE_STATUS          NUMBER,
  IS_ACCESSIBLE            NUMBER(1),
  REGION_NAME              VARCHAR2(100),
  HIERARCHY_LEVEL          NUMBER,
  HIERARCHY_PATH           VARCHAR2(4000),
  LAST_REFRESH_TS          TIMESTAMP WITH TIME ZONE NOT NULL
);
/

CREATE INDEX ADB_OCI_COMPARTMENTS_IX1
  ON ADB_OCI_COMPARTMENTS (PARENT_COMPARTMENT_OCID);
/

CREATE INDEX ADB_OCI_COMPARTMENTS_IX2
  ON ADB_OCI_COMPARTMENTS (LAST_REFRESH_TS);
/

CREATE INDEX ADB_OCI_COMPARTMENTS_IX3
  ON ADB_OCI_COMPARTMENTS (NAME);
/

--------------------------------------------------------------------------------
-- 3. REFRESH PROCEDURE
--------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE REFRESH_OCI_COMPARTMENTS
AS
  ------------------------------------------------------------------------------
  -- CHANGE THESE VALUES
  ------------------------------------------------------------------------------
  c_tenancy_id  CONSTANT VARCHAR2(500) := 'ocid1.tenancy.oc1..aaaaaaaaa3qmjxr43tjexx75r6gwk6vjw22ermohbw2vbxyhczksgjir7xdq';
  c_region      CONSTANT VARCHAR2(50)  := 'us-ashburn-1';
  c_credential  CONSTANT VARCHAR2(100) := 'OCI$RESOURCE_PRINCIPAL';
  c_page_size   CONSTANT NUMBER        := 1000;

  ------------------------------------------------------------------------------
  -- API OBJECTS
  ------------------------------------------------------------------------------
  response        DBMS_CLOUD_OCI_ID_IDENTITY_LIST_COMPARTMENTS_RESPONSE_T;
  response_body   DBMS_CLOUD_OCI_IDENTITY_COMPARTMENT_TBL;

  ------------------------------------------------------------------------------
  -- WORKING VARIABLES
  ------------------------------------------------------------------------------
  l_next_page     VARCHAR2(4000) := NULL;
  l_is_first      BOOLEAN        := TRUE;
  l_run_id        NUMBER;
  l_run_start     TIMESTAMP WITH TIME ZONE := SYSTIMESTAMP;
  l_rows_loaded   NUMBER := 0;
  l_errmsg        VARCHAR2(4000);
BEGIN
  ------------------------------------------------------------------------------
  -- START LOG
  ------------------------------------------------------------------------------
  INSERT INTO ADB_OCI_COMPARTMENTS_LOG (RUN_START_TS, STATUS)
  VALUES (l_run_start, 'RUNNING')
  RETURNING RUN_ID INTO l_run_id;

  COMMIT;

  ------------------------------------------------------------------------------
  -- FETCH COMPARTMENTS FROM OCI
  ------------------------------------------------------------------------------
  LOOP
    IF l_is_first THEN
      response := DBMS_CLOUD_OCI_ID_IDENTITY.LIST_COMPARTMENTS(
        compartment_id            => c_tenancy_id,
        limit                     => c_page_size,
        access_level              => 'ACCESSIBLE',
        compartment_id_in_subtree => 1,
        lifecycle_state           => 'ACTIVE',
        credential_name           => c_credential,
        region                    => c_region
      );
      l_is_first := FALSE;
    ELSE
      response := DBMS_CLOUD_OCI_ID_IDENTITY.LIST_COMPARTMENTS(
        compartment_id            => c_tenancy_id,
        limit                     => c_page_size,
        page                      => l_next_page,
        access_level              => 'ACCESSIBLE',
        compartment_id_in_subtree => 1,
        lifecycle_state           => 'ACTIVE',
        credential_name           => c_credential,
        region                    => c_region
      );
    END IF;

    response_body := response.response_body;

    IF response_body IS NOT NULL AND response_body.COUNT > 0 THEN
      FOR i IN 1 .. response_body.COUNT LOOP
        MERGE INTO ADB_OCI_COMPARTMENTS t
        USING (
          SELECT
            response_body(i).id                            AS compartment_ocid,
            response_body(i).compartment_id                AS parent_compartment_ocid,
            c_tenancy_id                                   AS tenancy_ocid,
            response_body(i).name                          AS name,
            response_body(i).description                   AS description,
            CAST(response_body(i).time_created AS TIMESTAMP WITH TIME ZONE) AS time_created,
            response_body(i).lifecycle_state               AS lifecycle_state,
            response_body(i).inactive_status               AS inactive_status,
            response_body(i).is_accessible                 AS is_accessible,
            c_region                                       AS region_name
          FROM dual
        ) s
        ON (t.COMPARTMENT_OCID = s.compartment_ocid)
        WHEN MATCHED THEN UPDATE SET
          t.PARENT_COMPARTMENT_OCID = s.parent_compartment_ocid,
          t.TENANCY_OCID            = s.tenancy_ocid,
          t.NAME                    = s.name,
          t.DESCRIPTION             = s.description,
          t.TIME_CREATED            = s.time_created,
          t.LIFECYCLE_STATE         = s.lifecycle_state,
          t.INACTIVE_STATUS         = s.inactive_status,
          t.IS_ACCESSIBLE           = s.is_accessible,
          t.REGION_NAME             = s.region_name,
          t.LAST_REFRESH_TS         = SYSTIMESTAMP
        WHEN NOT MATCHED THEN INSERT (
          COMPARTMENT_OCID,
          PARENT_COMPARTMENT_OCID,
          TENANCY_OCID,
          NAME,
          DESCRIPTION,
          TIME_CREATED,
          LIFECYCLE_STATE,
          INACTIVE_STATUS,
          IS_ACCESSIBLE,
          REGION_NAME,
          LAST_REFRESH_TS
        ) VALUES (
          s.compartment_ocid,
          s.parent_compartment_ocid,
          s.tenancy_ocid,
          s.name,
          s.description,
          s.time_created,
          s.lifecycle_state,
          s.inactive_status,
          s.is_accessible,
          s.region_name,
          SYSTIMESTAMP
        );

        l_rows_loaded := l_rows_loaded + 1;
      END LOOP;
    END IF;

    ----------------------------------------------------------------------------
    -- PAGINATION
    ----------------------------------------------------------------------------
    l_next_page := NULL;

    IF response.headers IS NOT NULL THEN
      IF response.headers.has('opc-next-page') THEN
        l_next_page := response.headers.get_string('opc-next-page');
      END IF;
    END IF;

    EXIT WHEN l_next_page IS NULL;
  END LOOP;

  ------------------------------------------------------------------------------
  -- ADD TENANCY ROOT ROW
  -- Requested extra row:
  -- compartment_ocid = tenancy_ocid
  -- parent_compartment_ocid = NULL  (safer than self-reference)
  -- tenancy_ocid = tenancy_ocid
  ------------------------------------------------------------------------------
  MERGE INTO ADB_OCI_COMPARTMENTS t
  USING (
    SELECT
      c_tenancy_id AS compartment_ocid,
      CAST(NULL AS VARCHAR2(500)) AS parent_compartment_ocid,
      c_tenancy_id AS tenancy_ocid,
      'TENANCY_ROOT' AS name,
      'Root tenancy node' AS description,
      SYSTIMESTAMP AS time_created,
      'ACTIVE' AS lifecycle_state,
      0 AS inactive_status,
      1 AS is_accessible,
      c_region AS region_name
    FROM dual
  ) s
  ON (t.COMPARTMENT_OCID = s.compartment_ocid)
  WHEN MATCHED THEN UPDATE SET
    t.PARENT_COMPARTMENT_OCID = s.parent_compartment_ocid,
    t.TENANCY_OCID            = s.tenancy_ocid,
    t.NAME                    = s.name,
    t.DESCRIPTION             = s.description,
    t.TIME_CREATED            = s.time_created,
    t.LIFECYCLE_STATE         = s.lifecycle_state,
    t.INACTIVE_STATUS         = s.inactive_status,
    t.IS_ACCESSIBLE           = s.is_accessible,
    t.REGION_NAME             = s.region_name,
    t.LAST_REFRESH_TS         = SYSTIMESTAMP
  WHEN NOT MATCHED THEN INSERT (
    COMPARTMENT_OCID,
    PARENT_COMPARTMENT_OCID,
    TENANCY_OCID,
    NAME,
    DESCRIPTION,
    TIME_CREATED,
    LIFECYCLE_STATE,
    INACTIVE_STATUS,
    IS_ACCESSIBLE,
    REGION_NAME,
    LAST_REFRESH_TS
  ) VALUES (
    s.compartment_ocid,
    s.parent_compartment_ocid,
    s.tenancy_ocid,
    s.name,
    s.description,
    s.time_created,
    s.lifecycle_state,
    s.inactive_status,
    s.is_accessible,
    s.region_name,
    SYSTIMESTAMP
  );

  ------------------------------------------------------------------------------
  -- BUILD HIERARCHY
  -- Fix for ORA-32039: recursive WITH must include column alias list
  ------------------------------------------------------------------------------
  MERGE INTO ADB_OCI_COMPARTMENTS t
  USING (
    WITH hier (compartment_ocid, parent_compartment_ocid, lvl, path) AS (
      SELECT
        compartment_ocid,
        parent_compartment_ocid,
        0 AS lvl,
        CAST(name AS VARCHAR2(4000)) AS path
      FROM ADB_OCI_COMPARTMENTS
      WHERE compartment_ocid = c_tenancy_id

      UNION ALL

      SELECT
        c.compartment_ocid,
        c.parent_compartment_ocid,
        h.lvl + 1 AS lvl,
        h.path || ' / ' || c.name AS path
      FROM ADB_OCI_COMPARTMENTS c
      JOIN hier h
        ON c.parent_compartment_ocid = h.compartment_ocid
      WHERE c.compartment_ocid <> c_tenancy_id
    )
    SELECT
      compartment_ocid,
      lvl,
      path
    FROM hier
  ) s
  ON (t.COMPARTMENT_OCID = s.compartment_ocid)
  WHEN MATCHED THEN UPDATE SET
    t.HIERARCHY_LEVEL = s.lvl,
    t.HIERARCHY_PATH  = s.path;

  ------------------------------------------------------------------------------
  -- MARK MISSING OLD ROWS AS DELETED
  ------------------------------------------------------------------------------
  UPDATE ADB_OCI_COMPARTMENTS
     SET LIFECYCLE_STATE = 'DELETED',
         LAST_REFRESH_TS = SYSTIMESTAMP
   WHERE LAST_REFRESH_TS < l_run_start
     AND LIFECYCLE_STATE <> 'DELETED';

  COMMIT;

  ------------------------------------------------------------------------------
  -- SUCCESS LOG
  ------------------------------------------------------------------------------
  UPDATE ADB_OCI_COMPARTMENTS_LOG
     SET RUN_END_TS  = SYSTIMESTAMP,
         STATUS      = 'SUCCESS',
         ROWS_LOADED = l_rows_loaded
   WHERE RUN_ID = l_run_id;

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    l_errmsg := SUBSTR(SQLERRM, 1, 4000);
    ROLLBACK;

    UPDATE ADB_OCI_COMPARTMENTS_LOG
       SET RUN_END_TS    = SYSTIMESTAMP,
           STATUS        = 'FAILED',
           ROWS_LOADED   = l_rows_loaded,
           ERROR_MESSAGE = l_errmsg
     WHERE RUN_ID = l_run_id;

    COMMIT;
    RAISE;
END REFRESH_OCI_COMPARTMENTS;
/
SHOW ERRORS;

--------------------------------------------------------------------------------
-- 4. RUN ONCE
--------------------------------------------------------------------------------
BEGIN
  REFRESH_OCI_COMPARTMENTS;
END;
/

--------------------------------------------------------------------------------
-- 5. VALIDATE
--------------------------------------------------------------------------------
SELECT
  STATUS,
  ROWS_LOADED,
  RUN_START_TS,
  RUN_END_TS,
  ERROR_MESSAGE
FROM ADB_OCI_COMPARTMENTS_LOG
ORDER BY RUN_ID DESC
FETCH FIRST 5 ROWS ONLY;
/

SELECT
  COUNT(*) AS total_compartments,
  COUNT(CASE WHEN HIERARCHY_PATH IS NULL THEN 1 END) AS missing_path,
  COUNT(CASE WHEN HIERARCHY_LEVEL IS NULL THEN 1 END) AS missing_level,
  MAX(HIERARCHY_LEVEL) AS max_depth
FROM ADB_OCI_COMPARTMENTS;
/


SELECT
  COMPARTMENT_OCID,
  PARENT_COMPARTMENT_OCID,
  TENANCY_OCID,
  NAME,
  HIERARCHY_LEVEL,
  HIERARCHY_PATH,
  LIFECYCLE_STATE
FROM ADB_OCI_COMPARTMENTS
ORDER BY HIERARCHY_LEVEL NULLS FIRST, HIERARCHY_PATH NULLS FIRST, NAME;
/

--------------------------------------------------------------------------------
-- 6. OPTIONAL SCHEDULER JOB
--------------------------------------------------------------------------------
BEGIN
  DBMS_SCHEDULER.CREATE_JOB (
    job_name        => 'JOB_REFRESH_OCI_COMPARTMENTS',
    job_type        => 'STORED_PROCEDURE',
    job_action      => 'REFRESH_OCI_COMPARTMENTS',
    start_date      => SYSTIMESTAMP,
    repeat_interval => 'FREQ=HOURLY; INTERVAL=1',
    enabled         => TRUE,
    auto_drop       => FALSE,
    comments        => 'Refresh OCI compartments every hour'
  );
END;
/

--------------------------------------------------------------------------------
-- 7. JOB CHECK
--------------------------------------------------------------------------------
SELECT
  JOB_NAME,
  ENABLED,
  STATE,
  LAST_START_DATE,
  LAST_RUN_DURATION,
  REPEAT_INTERVAL
FROM USER_SCHEDULER_JOBS
WHERE JOB_NAME = 'JOB_REFRESH_OCI_COMPARTMENTS';
/
